version: '3.8'
networks:
  politicians-explorer-network:
    driver: bridge

services:
  back:
    container_name: back
    build:
      context: ./back
      dockerfile: ./Dockerfile
    volumes:
      - ./back/src:/app/src
    depends_on:
      - elasticsearch
    networks:
      - politicians-explorer-network
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - '3000:3000'

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    networks:
      - politicians-explorer-network
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
